### ISSUE TITLE
Barrantes Issues

### ISSUE THREAD

**Issue by Sanchez-SamanthaNicole** [PUP-BSIT/ex7-tech_nx#1]
- **all files should be named in snake case, all lower case.**

Barrantes_SofiaAnne.html should be barrantes_sofiaanne.html

Please see this reference for your guide: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0

- **line column exceeded 80 lines of code.**

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/barrantes_sofiaanne/Barrantes_SofiaAnne.html#L46

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/barrantes_sofiaanne/Barrantes_SofiaAnne.html#L48

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/barrantes_sofiaanne/Barrantes_SofiaAnne.html#L49

Please see this reference for your guide: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

- **class name should be written in kebab-case**

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/barrantes_sofiaanne/Barrantes_SofiaAnne.html#L10

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/barrantes_sofiaanne/Barrantes_SofiaAnne.html#L16

Please see this reference for your guide: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

**Comment by barrantes-sofiaanne** [comment]
Thank you.
