### ISSUE TITLE
Alimasa's Issues (HTML and CSS)

### ISSUE THREAD

**Issue by Malaluan-KylaRica** [PUP-BSIT/ex7-tech_nx#2]
**all files should be named in snake case, all lower case.** 
--> ALIMASA.ELIZA.html should be alimasa_eliza.html

**observe proper indentation with your html file**
--> reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_50

**for html:** 
1. https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Alimasa_Eliza/ALIMASA_ELIZA.html#L18
--> avoid using br element
--> reference:  https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g28d48e53e08_0_139

2. https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Alimasa_Eliza/ALIMASA_ELIZA.html#L18
https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Alimasa_Eliza/ALIMASA_ELIZA.html#L52
--> exceeded to 80 columns
--> reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

3. https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Alimasa_Eliza/ALIMASA_ELIZA.html#L62-L64
https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Alimasa_Eliza/ALIMASA_ELIZA.html#L72-L74
https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Alimasa_Eliza/ALIMASA_ELIZA.html#L82-L84
https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Alimasa_Eliza/ALIMASA_ELIZA.html#L92-L94
https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Alimasa_Eliza/ALIMASA_ELIZA.html#L102-L104
--> remove the inline css inside the html file
--> reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g286f540102c_1_0

4. https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Alimasa_Eliza/ALIMASA_ELIZA.html#L46-L47
https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Alimasa_Eliza/ALIMASA_ELIZA.html#L57-L58
--> I suggest you should use lowercase for class names.
--> reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

**for css**
1. https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Alimasa_Eliza/style.css#L6-L10
--> proper indention (in closing bracket line 10)
--> reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_50

**Comment by ElizaAlimasa** [comment]
Thank you ^^

**Comment by Alimasa-Eliza** [comment]
Thank you!! ^^
