### ISSUE TITLE
Tayoto's Issues (HTML and CSS)

### ISSUE THREAD

**Issue by Rasquero-ViaClariz** [PUP-BSIT/ex7-tech_nx#3]
@Tayoto-Mikaella 

html file:

- file name should be named in snake case, all lower case.
see: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0.

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Tayoto_MikaellaAntonette/Tayoto_MikaellaAntonette.html#L6
--> id="main_body"
- IDs should be written in snake case, all lower case separated by underscore.
see: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Tayoto_MikaellaAntonette/Tayoto_MikaellaAntonette.html#L8
- always use lowercase for html elements.
see: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g286f540102c_1_0

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Tayoto_MikaellaAntonette/Tayoto_MikaellaAntonette.html#L38-L40
- exceeded 80 columns. 
see: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

css file:
https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Tayoto_MikaellaAntonette/style.css#L11
- id attribute should be in the snake case format. 
see: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/Tayoto_MikaellaAntonette/style.css#L15-L21
- separate every css block with a single space.
see: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35

**Comment by Tayoto-Mikaella** [comment]
Thank You!
