### ISSUE TITLE
Pasion Issues

### ISSUE THREAD

**Issue by Manzanas-MarkAngelo** [PUP-BSIT/ex7-tech_nx#4]
https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pasion_preciouskaye/Pasion_preciouskaye.html#L24

Class names should be written in kebab case. All lower case separated by hyphen.

Refer to coding guidelines: 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

___

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pasion_preciouskaye/Pasion_preciouskaye.html#L38-L41

Exceeded 80 columns.

Refer to coding guidelines:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

___

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pasion_preciouskaye/Pasion_preciouskaye.html#L42

Unordered list element with no content.

___

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pasion_preciouskaye/Pasion_preciouskaye.html#L50-L55

Images will only be displayed when html file is opened on local machine and won't work on other devices because local file path was assigned to the src attribute.

More info about file path: https://www.w3schools.com/html/html_filepaths.asp 

___

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pasion_preciouskaye/design.css

Observe proper indentation.

Refer to coding guidelines: 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_50

___

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pasion_preciouskaye/Pasion_preciouskaye.html

All files should be named in snake case, all lower case.

Refer to coding guidelines: 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0

**Comment by Pasionpreciouskaye** [comment]
Thank you
