### ISSUE TITLE
index.html Issues

### ISSUE THREAD

**Issue by Malaluan-KylaRica** [PUP-BSIT/ex7-tech_nx#5]
https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/index.html#L17
https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/index.html#L20
https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/index.html#L23
https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/index.html#L26

-->exceeded 80 columns, you can simply break it down or enter a new line.
--> reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

**Comment by barrantes-sofiaanne** [comment]
Thank you.
