### ISSUE TITLE
indexstyle.css Issue

### ISSUE THREAD

**Issue by Rasquero-ViaClariz** [PUP-BSIT/ex7-tech_nx#6]
- all files should be named in snake case, all lower case.
- --> index_style.css
see: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/indexstyle.css#L1-L9
- remove unnecessary space inside the body element without content in line 8

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/indexstyle.css#L11-L22
- observe proper indentation
see: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_50

**Comment by Tayoto-Mikaella** [comment]
Thank you!
