### ISSUE TITLE
Pepito's Issues (HTML and CSS)

### ISSUE THREAD

**Issue by Asebuque-ChrystineNoelle** [PUP-BSIT/ex7-tech_nx#7]
HTML FILE: 

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pepito_alonajane/pepito_alonajane.html#L15

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pepito_alonajane/pepito_alonajane.html#L28

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pepito_alonajane/pepito_alonajane.html#L51

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pepito_alonajane/pepito_alonajane.html#L52

- remove semi-colon
- Class names should be written in kebab case. (For line 28 and line 51)
See reference: 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pepito_alonajane/pepito_alonajane.html#L43

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pepito_alonajane/pepito_alonajane.html#L45-L47

- exceeded 80 columns
See reference:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

- Observe proper indentations in your html file
See reference:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_50

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pepito_alonajane/pepito_alonajane.html#L54-L58
- Images are not displaying because the file path location is only stored in the local machine.
See reference about file path:
https://www.w3schools.com/html/html_filepaths.asp

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pepito_alonajane/pepito_alonajane.html#L54-L58
- Remove the inline css inside the html file.
See reference: 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g286f540102c_1_0

CSS FILE:

- Observe proper indentations in your html file
See reference:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_50

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pepito_alonajane/style.css#L1-L9

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pepito_alonajane/style.css#L28-L42
- Remove unnecessary spaces.
See reference:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0

https://github.com/PUP-BSIT/ex7-tech_nx/blob/be777357dc860ce0fb3ec3ba3ab46cc63b6862a3/pepito_alonajane/style.css#L48-L56
- Remove unnecessary comments.
See reference:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

**Comment by pepito-alonajane** [comment]
Thank you po!
